[env:esp32s3box]
platform = espressif32
board = esp32s3box
framework = arduino

; Phân vùng bộ nhớ
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv

monitor_speed = 115200

; MỞ KHÓA SERIAL QUA CỔNG USB-C
build_flags = 
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1 
    -I include


lib_deps = 
    lovyan03/LovyanGFX @ ^1.1.12
    lewisxhe/XPowersLib@^0.2.1
    knolleary/PubSubClient@^2.8

